spring:
  profiles:
    active: -dev

---
#系统配置信息
server: 
  port: 8888
spring:
  profiles: authority
  application:
    name: cloud-config-authority
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority?characterEncoding=utf-8
    username: root
    password:
  #配置中心
  cloud:
    ###开始配置consul的服务注册
    consul:
      #consul服务器的主机地址
      host: localhost
      #consul服务器的ip地址
      port: 8500
      discovery:
        #服务主机名称
        #hostname: 127.0.0.1
        #服务的名称
        service-name: ${spring.application.name}
        #是否需要注册
        register: true
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ci.pojo

---
#网关配置
server:
  port: 7788
spring:
  profiles: gateway
  application:
    name: cloud-gateway
  cloud:
    #注册到consul注册中心
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
    #gateway网关路由配置
    gateway:
      routes:
        - id: gateway-service1  #我们自定义的路由 ID，保持唯一
          uri: lb://cloud-config-authority  #目标服务地址
          predicates:
          - Path=/**    #断言，条件满足则路由跳转

