spring:
  profiles:
    active: -dev

---
#系统配置信息
server: 
  port: 8888
spring:
  profiles: authority
  application:
    name: cloud-config-authority
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/authority?characterEncoding=utf-8
    username: root
    password:
  #配置中心
  cloud:
    ###开始配置consul的服务注册
    consul:
      #consul服务器的主机地址
      host: localhost
      #consul服务器的ip地址
      port: 8500
      discovery:
        #服务主机名称
        #hostname: 127.0.0.1
        #服务的名称
        service-name: ${spring.application.name}
        #是否需要注册
        register: true
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ci.pojo

---
#测试配置
spring:
  profiles: test
  application:
    name: cloud-config-test
